"""empty message

Revision ID: 9827b9a47ed4
Revises: 8831aa47cbbe
Create Date: 2021-01-02 23:56:44.189657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9827b9a47ed4'
down_revision = '8831aa47cbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('genres', sa.String(length=125), nullable=True),
    sa.Column('address', sa.String(length=123), nullable=True),
    sa.Column('city', sa.String(length=121), nullable=True),
    sa.Column('state', sa.String(length=122), nullable=True),
    sa.Column('phone', sa.String(length=124), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=126), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Venue')
    # ### end Alembic commands ###
